export class BookExample {
  static paginationExample = {
    limit: 10,
    page: 1,
    total: 30,
  };

  static postBookExample = {
    id: 'clxknfxxv000l4bwkvp7j1mdv',
    status: 'OPEN',
    finalPrice: 80000,
    recommendedPrice: 80000,
    description:
      'The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched.',
    seenCount: 0,
    createdAt: '2024-06-18T16:59:21.620Z',
    book: {
      id: 'clxknfxxw000m4bwk91epegvu',
      title: 'The Lean Startup',
      author: 'Eric Ries',
      ISBN: '9780307887894',
      publisher: 'Crown Business',
      publishYear: 2011,
      language: 'English',
      imageUrl:
        'https://storage.googleapis.com/bucket-storage-request/images/user/CJWuRWiybje4V63JqMYdw0XNru83/CJWuRWiybje4V63JqMYdw0XNru83.png',
      buyPrice: 100000,
      predictionResults: {
        id: 'clxknfxxw000n4bwk3aduvcs9',
        bookCondition: 'QUITE_GOOD',
        buyPrice: 100000,
        outputPrice: 80000,
        percentage: 80,
        rippedRatio: 0.2,
        wornOutRatio: 0.2,
        overallRatio: 0.8,
      },
    },
    user: {
      id: 'clxknfuoj00004bwkz18ibxsx',
      profile: {
        id: 'clxknfuom00024bwknpy2ria8',
        name: 'John Doe',
        avatarUrl: 'https://picsum.photos/200',
        phoneNumber: '+6281234567890',
        adminAreaLocality: 'Jawa Timur',
        cityLocality: 'Surabaya',
        address: 'Jl. Raya Darmo Permai III',
      },
    },
  };

  static openSaleBookExample = [
    {
      id: 'clxknfvja00094bwkzs3ogfy8',
      status: 'OPEN',
      finalPrice: 80000,
      recommendedPrice: 80000,
      description:
        'The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched.',
      seenCount: 0,
      createdAt: '2024-06-18T16:59:18.502Z',
      book: {
        id: 'clxknfvja000a4bwk8gk4emzq',
        title: 'The Lean Startup',
        author: 'Eric Ries',
        ISBN: '9780307887894',
        publisher: 'Crown Business',
        publishYear: 2011,
        language: 'English',
        imageUrl:
          'https://storage.googleapis.com/bucket-storage-request/images/user/CJWuRWiybje4V63JqMYdw0XNru83/CJWuRWiybje4V63JqMYdw0XNru83.png',
        buyPrice: 100000,
        predictionResults: {
          id: 'clxknfvja000b4bwkzi8aoq5n',
          bookCondition: 'QUITE_GOOD',
          buyPrice: 100000,
          outputPrice: 80000,
          percentage: 80,
          rippedRatio: 0.2,
          wornOutRatio: 0.2,
          overallRatio: 0.8,
        },
      },
      user: {
        id: 'clxknfuoj00004bwkz18ibxsx',
        profile: {
          id: 'clxknfuom00024bwknpy2ria8',
          name: 'John Doe',
          avatarUrl: 'https://picsum.photos/200',
          phoneNumber: '+6281234567890',
          adminAreaLocality: 'Jawa Timur',
          cityLocality: 'Surabaya',
          address: 'Jl. Raya Darmo Permai III',
        },
      },
    },
    {
      id: 'clxknfwjc000c4bwk6aimhz5a',
      status: 'OPEN',
      finalPrice: 80000,
      recommendedPrice: 80000,
      description:
        'The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched.',
      seenCount: 0,
      createdAt: '2024-06-18T16:59:19.800Z',
      book: {
        id: 'clxknfwjc000d4bwkkv95les1',
        title: 'The Lean Startup',
        author: 'Eric Ries',
        ISBN: '9780307887894',
        publisher: 'Crown Business',
        publishYear: 2011,
        language: 'English',
        imageUrl:
          'https://storage.googleapis.com/bucket-storage-request/images/user/CJWuRWiybje4V63JqMYdw0XNru83/CJWuRWiybje4V63JqMYdw0XNru83.png',
        buyPrice: 100000,
        predictionResults: {
          id: 'clxknfwjc000e4bwkwbcswqfb',
          bookCondition: 'QUITE_GOOD',
          buyPrice: 100000,
          outputPrice: 80000,
          percentage: 80,
          rippedRatio: 0.2,
          wornOutRatio: 0.2,
          overallRatio: 0.8,
        },
      },
      user: {
        id: 'clxknfuoj00004bwkz18ibxsx',
        profile: {
          id: 'clxknfuom00024bwknpy2ria8',
          name: 'John Doe',
          avatarUrl: 'https://picsum.photos/200',
          phoneNumber: '+6281234567890',
          adminAreaLocality: 'Jawa Timur',
          cityLocality: 'Surabaya',
          address: 'Jl. Raya Darmo Permai III',
        },
      },
    },
    {
      id: 'clxknfx1f000f4bwksqsgprgx',
      status: 'OPEN',
      finalPrice: 80000,
      recommendedPrice: 80000,
      description:
        'The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched.',
      seenCount: 0,
      createdAt: '2024-06-18T16:59:20.451Z',
      book: {
        id: 'clxknfx1f000g4bwkt8dgrsq4',
        title: 'The Lean Startup',
        author: 'Eric Ries',
        ISBN: '9780307887894',
        publisher: 'Crown Business',
        publishYear: 2011,
        language: 'English',
        imageUrl:
          'https://storage.googleapis.com/bucket-storage-request/images/user/CJWuRWiybje4V63JqMYdw0XNru83/CJWuRWiybje4V63JqMYdw0XNru83.png',
        buyPrice: 100000,
        predictionResults: {
          id: 'clxknfx1f000h4bwkizd55fqp',
          bookCondition: 'QUITE_GOOD',
          buyPrice: 100000,
          outputPrice: 80000,
          percentage: 80,
          rippedRatio: 0.2,
          wornOutRatio: 0.2,
          overallRatio: 0.8,
        },
      },
      user: {
        id: 'clxknfuoj00004bwkz18ibxsx',
        profile: {
          id: 'clxknfuom00024bwknpy2ria8',
          name: 'John Doe',
          avatarUrl: 'https://picsum.photos/200',
          phoneNumber: '+6281234567890',
          adminAreaLocality: 'Jawa Timur',
          cityLocality: 'Surabaya',
          address: 'Jl. Raya Darmo Permai III',
        },
      },
    },
    {
      id: 'clxknfxm1000i4bwkga4e2n8g',
      status: 'OPEN',
      finalPrice: 80000,
      recommendedPrice: 80000,
      description:
        'The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched.',
      seenCount: 0,
      createdAt: '2024-06-18T16:59:21.194Z',
      book: {
        id: 'clxknfxm1000j4bwkh0ij0mho',
        title: 'The Lean Startup',
        author: 'Eric Ries',
        ISBN: '9780307887894',
        publisher: 'Crown Business',
        publishYear: 2011,
        language: 'English',
        imageUrl:
          'https://storage.googleapis.com/bucket-storage-request/images/user/CJWuRWiybje4V63JqMYdw0XNru83/CJWuRWiybje4V63JqMYdw0XNru83.png',
        buyPrice: 100000,
        predictionResults: {
          id: 'clxknfxm1000k4bwkpm8ls6qq',
          bookCondition: 'QUITE_GOOD',
          buyPrice: 100000,
          outputPrice: 80000,
          percentage: 80,
          rippedRatio: 0.2,
          wornOutRatio: 0.2,
          overallRatio: 0.8,
        },
      },
      user: {
        id: 'clxknfuoj00004bwkz18ibxsx',
        profile: {
          id: 'clxknfuom00024bwknpy2ria8',
          name: 'John Doe',
          avatarUrl: 'https://picsum.photos/200',
          phoneNumber: '+6281234567890',
          adminAreaLocality: 'Jawa Timur',
          cityLocality: 'Surabaya',
          address: 'Jl. Raya Darmo Permai III',
        },
      },
    },
    {
      id: 'clxknfxxv000l4bwkvp7j1mdv',
      status: 'OPEN',
      finalPrice: 80000,
      recommendedPrice: 80000,
      description:
        'The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched.',
      seenCount: 0,
      createdAt: '2024-06-18T16:59:21.620Z',
      book: {
        id: 'clxknfxxw000m4bwk91epegvu',
        title: 'The Lean Startup',
        author: 'Eric Ries',
        ISBN: '9780307887894',
        publisher: 'Crown Business',
        publishYear: 2011,
        language: 'English',
        imageUrl:
          'https://storage.googleapis.com/bucket-storage-request/images/user/CJWuRWiybje4V63JqMYdw0XNru83/CJWuRWiybje4V63JqMYdw0XNru83.png',
        buyPrice: 100000,
        predictionResults: {
          id: 'clxknfxxw000n4bwk3aduvcs9',
          bookCondition: 'QUITE_GOOD',
          buyPrice: 100000,
          outputPrice: 80000,
          percentage: 80,
          rippedRatio: 0.2,
          wornOutRatio: 0.2,
          overallRatio: 0.8,
        },
      },
      user: {
        id: 'clxknfuoj00004bwkz18ibxsx',
        profile: {
          id: 'clxknfuom00024bwknpy2ria8',
          name: 'John Doe',
          avatarUrl: 'https://picsum.photos/200',
          phoneNumber: '+6281234567890',
          adminAreaLocality: 'Jawa Timur',
          cityLocality: 'Surabaya',
          address: 'Jl. Raya Darmo Permai III',
        },
      },
    },
    {
      id: 'clxknfy8c000o4bwkk0abl284',
      status: 'OPEN',
      finalPrice: 80000,
      recommendedPrice: 80000,
      description:
        'The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched.',
      seenCount: 0,
      createdAt: '2024-06-18T16:59:21.996Z',
      book: {
        id: 'clxknfy8c000p4bwkwibh2q68',
        title: 'The Lean Startup',
        author: 'Eric Ries',
        ISBN: '9780307887894',
        publisher: 'Crown Business',
        publishYear: 2011,
        language: 'English',
        imageUrl:
          'https://storage.googleapis.com/bucket-storage-request/images/user/CJWuRWiybje4V63JqMYdw0XNru83/CJWuRWiybje4V63JqMYdw0XNru83.png',
        buyPrice: 100000,
        predictionResults: {
          id: 'clxknfy8c000q4bwkuwqxbnbu',
          bookCondition: 'QUITE_GOOD',
          buyPrice: 100000,
          outputPrice: 80000,
          percentage: 80,
          rippedRatio: 0.2,
          wornOutRatio: 0.2,
          overallRatio: 0.8,
        },
      },
      user: {
        id: 'clxknfuoj00004bwkz18ibxsx',
        profile: {
          id: 'clxknfuom00024bwknpy2ria8',
          name: 'John Doe',
          avatarUrl: 'https://picsum.photos/200',
          phoneNumber: '+6281234567890',
          adminAreaLocality: 'Jawa Timur',
          cityLocality: 'Surabaya',
          address: 'Jl. Raya Darmo Permai III',
        },
      },
    },
    {
      id: 'clxknfyif000r4bwkdcs0fimj',
      status: 'OPEN',
      finalPrice: 80000,
      recommendedPrice: 80000,
      description:
        'The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched.',
      seenCount: 0,
      createdAt: '2024-06-18T16:59:22.360Z',
      book: {
        id: 'clxknfyif000s4bwkq08d1yz7',
        title: 'The Lean Startup',
        author: 'Eric Ries',
        ISBN: '9780307887894',
        publisher: 'Crown Business',
        publishYear: 2011,
        language: 'English',
        imageUrl:
          'https://storage.googleapis.com/bucket-storage-request/images/user/CJWuRWiybje4V63JqMYdw0XNru83/CJWuRWiybje4V63JqMYdw0XNru83.png',
        buyPrice: 100000,
        predictionResults: {
          id: 'clxknfyif000t4bwkkvkqg2xj',
          bookCondition: 'QUITE_GOOD',
          buyPrice: 100000,
          outputPrice: 80000,
          percentage: 80,
          rippedRatio: 0.2,
          wornOutRatio: 0.2,
          overallRatio: 0.8,
        },
      },
      user: {
        id: 'clxknfuoj00004bwkz18ibxsx',
        profile: {
          id: 'clxknfuom00024bwknpy2ria8',
          name: 'John Doe',
          avatarUrl: 'https://picsum.photos/200',
          phoneNumber: '+6281234567890',
          adminAreaLocality: 'Jawa Timur',
          cityLocality: 'Surabaya',
          address: 'Jl. Raya Darmo Permai III',
        },
      },
    },
    {
      id: 'clxknfysi000u4bwkx9yp6vbn',
      status: 'OPEN',
      finalPrice: 80000,
      recommendedPrice: 80000,
      description:
        'The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched.',
      seenCount: 0,
      createdAt: '2024-06-18T16:59:22.723Z',
      book: {
        id: 'clxknfysj000v4bwkeucwu780',
        title: 'The Lean Startup',
        author: 'Eric Ries',
        ISBN: '9780307887894',
        publisher: 'Crown Business',
        publishYear: 2011,
        language: 'English',
        imageUrl:
          'https://storage.googleapis.com/bucket-storage-request/images/user/CJWuRWiybje4V63JqMYdw0XNru83/CJWuRWiybje4V63JqMYdw0XNru83.png',
        buyPrice: 100000,
        predictionResults: {
          id: 'clxknfysj000w4bwkfqzyjvnc',
          bookCondition: 'QUITE_GOOD',
          buyPrice: 100000,
          outputPrice: 80000,
          percentage: 80,
          rippedRatio: 0.2,
          wornOutRatio: 0.2,
          overallRatio: 0.8,
        },
      },
      user: {
        id: 'clxknfuoj00004bwkz18ibxsx',
        profile: {
          id: 'clxknfuom00024bwknpy2ria8',
          name: 'John Doe',
          avatarUrl: 'https://picsum.photos/200',
          phoneNumber: '+6281234567890',
          adminAreaLocality: 'Jawa Timur',
          cityLocality: 'Surabaya',
          address: 'Jl. Raya Darmo Permai III',
        },
      },
    },
    {
      id: 'clxknfz1w000x4bwkbpfyiy96',
      status: 'OPEN',
      finalPrice: 80000,
      recommendedPrice: 80000,
      description:
        'The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched.',
      seenCount: 0,
      createdAt: '2024-06-18T16:59:23.060Z',
      book: {
        id: 'clxknfz1w000y4bwk0ix71v2u',
        title: 'The Lean Startup',
        author: 'Eric Ries',
        ISBN: '9780307887894',
        publisher: 'Crown Business',
        publishYear: 2011,
        language: 'English',
        imageUrl:
          'https://storage.googleapis.com/bucket-storage-request/images/user/CJWuRWiybje4V63JqMYdw0XNru83/CJWuRWiybje4V63JqMYdw0XNru83.png',
        buyPrice: 100000,
        predictionResults: {
          id: 'clxknfz1w000z4bwk0sw9rd6d',
          bookCondition: 'QUITE_GOOD',
          buyPrice: 100000,
          outputPrice: 80000,
          percentage: 80,
          rippedRatio: 0.2,
          wornOutRatio: 0.2,
          overallRatio: 0.8,
        },
      },
      user: {
        id: 'clxknfuoj00004bwkz18ibxsx',
        profile: {
          id: 'clxknfuom00024bwknpy2ria8',
          name: 'John Doe',
          avatarUrl: 'https://picsum.photos/200',
          phoneNumber: '+6281234567890',
          adminAreaLocality: 'Jawa Timur',
          cityLocality: 'Surabaya',
          address: 'Jl. Raya Darmo Permai III',
        },
      },
    },
    {
      id: 'clxknfzc300104bwks84q39pt',
      status: 'OPEN',
      finalPrice: 80000,
      recommendedPrice: 80000,
      description:
        'The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched.',
      seenCount: 0,
      createdAt: '2024-06-18T16:59:23.428Z',
      book: {
        id: 'clxknfzc300114bwkc0tswlnz',
        title: 'The Lean Startup',
        author: 'Eric Ries',
        ISBN: '9780307887894',
        publisher: 'Crown Business',
        publishYear: 2011,
        language: 'English',
        imageUrl:
          'https://storage.googleapis.com/bucket-storage-request/images/user/CJWuRWiybje4V63JqMYdw0XNru83/CJWuRWiybje4V63JqMYdw0XNru83.png',
        buyPrice: 100000,
        predictionResults: {
          id: 'clxknfzc300124bwk9ha0p65f',
          bookCondition: 'QUITE_GOOD',
          buyPrice: 100000,
          outputPrice: 80000,
          percentage: 80,
          rippedRatio: 0.2,
          wornOutRatio: 0.2,
          overallRatio: 0.8,
        },
      },
      user: {
        id: 'clxknfuoj00004bwkz18ibxsx',
        profile: {
          id: 'clxknfuom00024bwknpy2ria8',
          name: 'John Doe',
          avatarUrl: 'https://picsum.photos/200',
          phoneNumber: '+6281234567890',
          adminAreaLocality: 'Jawa Timur',
          cityLocality: 'Surabaya',
          address: 'Jl. Raya Darmo Permai III',
        },
      },
    },
  ];
}
