name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "master", "prod" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master", "prod" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Create env file'
        run: |
          touch .env
          echo DATABASE_URL="${{ secrets.DATABASE_URL }}" >> .env
          echo FIREBASE_FILE="${{ secrets.FIREBASE_FILE }}" >> .env
          echo JWT_SECRET="${{ secrets.JWT_SECRET }}" >> .env
          echo SALT_ROUNDS="${{ secrets.SALT_ROUNDS }}" >> .env
          cat .env
        
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: bacalagi-be:latest
          load: true
          push: false
          secrets: |
            "DATABASE_URL=${{ secrets.DATABASE_URL }}"
            "FIREBASE_FILE=${{ secrets.FIREBASE_FILE }}"
            "JWT_SECRET=${{ secrets.JWT_SECRET }}"
            "SALT_ROUNDS=${{ secrets.SALT_ROUNDS }}"

      - name: Run Docker container
        uses: addnab/docker-run-action@v3
        with:
          image: bacalagi-be:latest
          options: --name bacalagi-be -p 3000:3000 -e DATABASE_URL=${{ secrets.DATABASE_URL }}
          run: echo "Container bacalagi-be Created 💪"

        
      
